<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Clinic.Authority.Domain\Clinic.Authority.Domain.csproj" />
        <ProjectReference Include="..\..\Contracts\Clinic.Contracts\Clinic.Contracts.csproj" />
    </ItemGroup>

</Project>