<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Client\Clinic.Client.Infrastructure\Clinic.Client.Infrastructure.csproj" />
        <ProjectReference Include="..\..\..\src\Client\Clinic.Client.Application\Clinic.Client.Application.csproj" />
        <ProjectReference Include="..\..\..\src\Authority\Clinic.Authority.Infrastructure\Clinic.Authority.Infrastructure.csproj" />
    </ItemGroup>

</Project>