CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE appointments (
    "Id" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "ScheduledAtUtc" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_appointments" PRIMARY KEY ("Id")
);

CREATE TABLE audit_log_entries (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OperationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "WorkstationId" uuid NOT NULL,
    "AggregateType" character varying(128) NOT NULL,
    "AggregateId" uuid NOT NULL,
    "ActionName" character varying(128) NOT NULL,
    "DetailJson" text NOT NULL,
    "AtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_audit_log_entries" PRIMARY KEY ("Id")
);

CREATE TABLE authoritative_changes (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OperationId" uuid NOT NULL,
    "AggregateType" character varying(128) NOT NULL,
    "AggregateId" uuid NOT NULL,
    "Version" bigint NOT NULL,
    "CommandType" character varying(128) NOT NULL,
    "ChangeJson" text NOT NULL,
    "OccurredAtUtc" timestamp with time zone NOT NULL,
    "Published" boolean NOT NULL,
    CONSTRAINT "PK_authoritative_changes" PRIMARY KEY ("Id")
);

CREATE TABLE patient_flow_entries (
    "Id" uuid NOT NULL,
    "AppointmentId" uuid NOT NULL,
    "PatientId" uuid NOT NULL,
    "DoctorId" uuid NOT NULL,
    "QueuedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_patient_flow_entries" PRIMARY KEY ("Id")
);

CREATE TABLE processed_operations (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WorkstationId" uuid NOT NULL,
    "OperationId" uuid NOT NULL,
    "CommandType" character varying(128) NOT NULL,
    "AggregateType" character varying(128) NOT NULL,
    "AggregateId" uuid NOT NULL,
    "ResultingVersion" bigint,
    "ProcessedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_processed_operations" PRIMARY KEY ("Id")
);

CREATE TABLE users (
    "Id" uuid NOT NULL,
    "Username" character varying(128) NOT NULL,
    "DisplayName" character varying(256) NOT NULL,
    "Role" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE TABLE workstations (
    "Id" uuid NOT NULL,
    "DisplayName" character varying(128) NOT NULL,
    "TrustState" integer NOT NULL,
    CONSTRAINT "PK_workstations" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_audit_log_entries_OperationId" ON audit_log_entries ("OperationId");

CREATE INDEX "IX_authoritative_changes_AggregateType_AggregateId" ON authoritative_changes ("AggregateType", "AggregateId");

CREATE INDEX "IX_patient_flow_entries_DoctorId_QueuedAtUtc" ON patient_flow_entries ("DoctorId", "QueuedAtUtc");

CREATE UNIQUE INDEX "IX_processed_operations_WorkstationId_OperationId" ON processed_operations ("WorkstationId", "OperationId");

CREATE UNIQUE INDEX "IX_users_Username" ON users ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260917123427_InitialAuthorityCreate', '10.0.4');

COMMIT;

